### ISSUE TITLE
Where can I get links for .s and .free?

### ISSUE THREAD

**Issue by fjaokdp** [V3RDAD/I2P_P_P#1]
![fs](https://user-images.githubusercontent.com/90276506/233659499-97451843-d33d-4c0d-a88c-0d02bac8b216.png)

**Comment by fjaokdp** [comment]
![1](https://user-images.githubusercontent.com/90276506/233664652-65c20144-01c2-491d-9a17-f0360ebe7b62.png)

**Comment by V3RDAD** [comment]
Hello, in I2P there is no recognized global namespace, you decide what any given .i2p domain maps to in the end using address helper. Unless I send you the base64 binding address you won't be able to connect to it. However you are free to create a service in tunnel manager with whatever domain I2P++ supports. As I2P++ is a new modification there has not been any community who has services up and running 24/7 to my knowledge.
